export const STATIC_LAWS = [
  /* ---- EUROPEAN UNION ---- */
  {
    name: 'EU Corporate Sustainability Due Diligence Directive',
    shortName: 'EU CSDDD',
    slug: 'eu-csddd',
    jurisdiction: 'European Union',
    region: 'European Union',
    status: 'In force',
    statusType: 'force',
    lastUpdated: '2026-06-01',
    tableUpdateText: 'Transposition deadline extended to July 2027',
    enactedDate: 'July 2024',
    firstComplianceDeadline: 'July 2027 (large companies)',
    companiesInScope: 'Companies with 1,000+ employees and EUR 450m+ turnover globally; lower thresholds for high-risk sectors',
    maxPenalty: '5% of global net turnover',
    civilLiability: 'Yes, civil liability for victims',
    enforcementBody: 'National supervisory authorities',
    sectorsAffected: ['Garments and textiles', 'Agriculture and food', 'Mining and extractives', 'Construction', 'Financial services'],
    supplierCountries: ['India', 'Bangladesh', 'Vietnam', 'Ethiopia', 'Kenya', 'Sri Lanka', 'Pakistan', 'Indonesia', 'Ghana', 'Tanzania'],
    summary: [
      { type: 'paragraph', text: 'The EU Corporate Sustainability Due Diligence Directive (CSDDD) is the most consequential piece of HREDD legislation passed in a generation. It requires large companies operating in the EU to conduct ongoing due diligence across their upstream supply chains and, for some sectors, their downstream distribution chains. For suppliers in the Global South, this means your buyers will be legally required to understand and address human rights and environmental risks connected to your operations.' },
      { type: 'paragraph', text: 'The Directive entered into force in July 2024. EU member states now have until July 2027 to transpose it into national law, after the original transposition deadline was extended by one year. Companies will be required to comply on a phased schedule based on size, beginning with the largest companies in 2027 and extending to smaller in-scope companies through 2029.' },
      { type: 'paragraph', text: 'For suppliers, the most immediate practical effect is likely to be increased information requests from buyers. Companies subject to the CSDDD must map their supply chains, assess risks, and take meaningful prevention and remediation measures. They cannot do this without cooperation from their suppliers. Whether that cooperation is structured as partnership or as a compliance burden largely depends on your buyer relationships and your own capacity to document your practices.' },
    ],
    obligations: [
      { title: 'Adopt a due diligence policy', detail: 'Companies must adopt and maintain a due diligence policy, updated annually, describing their approach to due diligence across their operations and value chains.' },
      { title: 'Map and assess adverse impacts', detail: 'Companies must identify actual and potential adverse human rights and environmental impacts in their own operations and those of their subsidiaries and business partners across the supply chain.' },
      { title: 'Prevent and mitigate potential impacts', detail: 'Where potential adverse impacts are identified, companies must take appropriate measures to prevent or mitigate them, including through contractual assurances from business partners.' },
      { title: 'Cease, remediate, and restore for actual impacts', detail: 'Where actual adverse impacts occur, companies must cease the activity causing the harm, or where cessation is not possible, minimise the impact and provide remediation to those affected.' },
      { title: 'Establish a complaints and notification procedure', detail: 'Companies must establish a procedure for persons and organisations to submit complaints where they have legitimate concerns about actual or potential adverse impacts.' },
      { title: 'Monitor due diligence effectiveness', detail: 'Companies must periodically assess the effectiveness of their due diligence policy and measures, at least once a year.' },
      { title: 'Communicate publicly', detail: 'Companies must report on their due diligence annually, in a manner consistent with the Corporate Sustainability Reporting Directive (CSRD) where applicable.' },
    ],
    timeline: [
      { date: 'July 2024', event: 'Directive enters into force', detail: 'The CSDDD was published in the Official Journal of the EU and entered into force.', isFuture: false },
      { date: 'July 2027 (extended)', event: 'Transposition deadline', detail: 'EU member states must incorporate the Directive into national law by this date. The original deadline was July 2026; it was extended by the European Commission.', isFuture: true },
      { date: 'Q3 2027', event: 'First companies in scope', detail: 'Companies with 5,000+ employees and EUR 1.5bn+ turnover must comply.', isFuture: true },
      { date: '2028', event: 'Second tier in scope', detail: 'Companies with 3,000+ employees and EUR 900m+ turnover must comply.', isFuture: true },
      { date: '2029', event: 'Full scope', detail: 'All in-scope companies, including those with 1,000+ employees and EUR 450m+ turnover, must comply.', isFuture: true },
    ],
    changelog: [
      { date: '2026-06-01', summary: 'Transposition deadline officially extended to July 2027', detail: 'The European Commission formally extended the transposition deadline from July 2026 to July 2027. The extension was granted following lobbying from several member state governments and business associations citing implementation complexity. Civil society organisations noted that the extension delays protections for workers and communities in supply chains.' },
      { date: '2025-09-15', summary: 'Commission publishes guidance on supply chain mapping methodology', detail: 'The European Commission released non-binding guidance on how companies should approach supply chain mapping under the CSDDD. The guidance acknowledges that full supply chain traceability is not always immediately achievable and allows for a risk-based approach that prioritises higher-risk tiers.' },
    ],
    sources: [
      { type: 'Official text', title: 'Directive (EU) 2024/1760 of the European Parliament and of the Council', url: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32024L1760', organisation: 'EUR-Lex' },
      { type: 'Guidance', title: 'Commission guidance on supply chain mapping', url: 'https://ec.europa.eu/', organisation: 'European Commission' },
    ],
    order: 1,
  },
  {
    name: 'EU Deforestation Regulation',
    shortName: 'EUDR',
    slug: 'eu-deforestation-regulation',
    jurisdiction: 'European Union',
    region: 'European Union',
    status: 'Delayed',
    statusType: 'delayed',
    lastUpdated: '2026-06-01',
    tableUpdateText: 'Implementation pushed to December 2026',
    enactedDate: 'June 2023',
    firstComplianceDeadline: 'December 2026 (revised)',
    companiesInScope: 'All operators and traders placing or exporting specified commodities from the EU',
    maxPenalty: '4% of total annual turnover in the EU',
    civilLiability: 'No direct civil liability',
    enforcementBody: 'National competent authorities',
    sectorsAffected: ['Cattle', 'Cocoa', 'Coffee', 'Palm oil', 'Soy', 'Wood', 'Rubber and derived products'],
    supplierCountries: ['Brazil', 'Indonesia', 'Malaysia', 'Ghana', 'Ivory Coast', 'Ethiopia', 'Uganda', 'Peru', 'Colombia'],
    summary: [
      { type: 'paragraph', text: 'The EU Deforestation Regulation (EUDR) prohibits the import and export of certain commodities unless they can be shown to have not contributed to deforestation or forest degradation after 31 December 2020. It applies to cattle, cocoa, coffee, palm oil, soy, wood, rubber, and products derived from these commodities.' },
      { type: 'paragraph', text: 'The original implementation date of 30 December 2024 was postponed by one year following significant political pressure, particularly from producer country governments and industry associations. The revised deadline is December 2026, though the underlying regulation remains in force.' },
      { type: 'paragraph', text: 'For suppliers in forest-adjacent supply chains, the practical requirement is geolocation data linking commodities to their production plots, plus documentation establishing that those plots were not forested after December 2020. This is a significant data infrastructure requirement that many smallholder-based supply chains are not currently equipped to meet.' },
    ],
    obligations: [
      { title: 'Geolocation documentation', detail: 'Operators must collect and maintain geolocation data for all production plots supplying regulated commodities.' },
      { title: 'Due diligence statement', detail: 'Operators must submit a due diligence statement to EU customs authorities before placing or exporting products on the EU market.' },
      { title: 'No deforestation assurance', detail: 'All regulated commodities must be shown to have been produced on land that was not subject to deforestation or forest degradation after 31 December 2020.' },
      { title: 'Legal production assurance', detail: 'Commodities must comply with all applicable laws in the country of production, including land rights, labour rights, and environmental regulations.' },
    ],
    timeline: [
      { date: 'June 2023', event: 'Regulation enters into force', detail: 'The EUDR was published in the Official Journal and entered into force.', isFuture: false },
      { date: 'December 2024', event: 'Original compliance deadline (missed)', detail: 'The original deadline was postponed by one year due to implementation concerns.', isFuture: false },
      { date: 'December 2026', event: 'Revised compliance deadline', detail: 'Large operators must be fully compliant by this date. SMEs have until June 2027.', isFuture: true },
    ],
    changelog: [
      { date: '2026-01-15', summary: 'Benchmarking system for country risk classification published', detail: 'The European Commission published its country benchmarking system classifying countries as low, standard, or high risk for deforestation. Several producing countries have contested their risk classifications.' },
    ],
    sources: [
      { type: 'Official text', title: 'Regulation (EU) 2023/1115', url: 'https://eur-lex.europa.eu/', organisation: 'EUR-Lex' },
    ],
    order: 2,
  },
  {
    name: 'EU Forced Labour Regulation',
    shortName: 'EU FLR',
    slug: 'eu-forced-labour-regulation',
    jurisdiction: 'European Union',
    region: 'European Union',
    status: 'In force',
    statusType: 'force',
    lastUpdated: '2026-06-01',
    tableUpdateText: 'First investigation announced',
    enactedDate: 'November 2024',
    firstComplianceDeadline: 'November 2027',
    companiesInScope: 'Any company placing products on the EU market where forced labour is suspected',
    maxPenalty: 'Withdrawal and destruction of product; fines up to 4% of global turnover',
    civilLiability: 'No direct civil liability',
    enforcementBody: 'European Commission (for global supply chains) and national authorities',
    sectorsAffected: ['All sectors with known forced labour risk', 'Electronics', 'Textiles', 'Agriculture', 'Mining'],
    supplierCountries: ['China (Xinjiang)', 'North Korea', 'Eritrea', 'Uzbekistan', 'Turkmenistan', 'Brazil (Cerrado)', 'Myanmar'],
    summary: [
      { type: 'paragraph', text: 'The EU Forced Labour Regulation bans products made with forced labour from the EU market. Unlike the CSDDD, which focuses on company process obligations, this regulation targets products themselves. Any product where a competent authority finds that forced labour was used in production can be prohibited from sale and must be withdrawn from the market.' },
      { type: 'paragraph', text: 'The regulation creates a two-track enforcement system: the European Commission handles investigations into forced labour linked to state-imposed practices or affecting supply chains across multiple member states, while national authorities handle cases within their jurisdictions.' },
      { type: 'paragraph', text: 'For most Global South suppliers, the regulation is most immediately relevant if you supply into sectors or geographies that have been identified as high risk. The first investigations, expected to focus on products linked to state-imposed forced labour programmes, will establish the template for how the regulation is enforced.' },
    ],
    obligations: [
      { title: 'No forced labour in supply chain', detail: 'Products where forced labour has been used at any stage of production or extraction cannot be placed on the EU market.' },
      { title: 'Respond to competent authority investigations', detail: 'Companies subject to investigation must cooperate with competent authorities and provide all relevant information and documentation.' },
      { title: 'Withdraw non-compliant products', detail: 'If a product is found to have been made with forced labour, operators must withdraw it from the EU market and may be required to destroy it.' },
    ],
    timeline: [
      { date: 'November 2024', event: 'Regulation enters into force', detail: 'The Forced Labour Regulation was published and entered into force.', isFuture: false },
      { date: 'June 2026', event: 'First investigation announced', detail: 'The European Commission announced its first formal investigation under the regulation.', isFuture: false },
      { date: 'November 2027', event: 'Full enforcement begins', detail: 'All provisions, including national authority enforcement, fully operational.', isFuture: true },
    ],
    changelog: [
      { date: '2026-06-01', summary: 'First investigation formally announced', detail: 'The European Commission announced the first formal investigation under the EU Forced Labour Regulation. The investigation targets a specific product category and focuses on a supply chain with documented state-imposed forced labour risks.' },
    ],
    sources: [
      { type: 'Official text', title: 'Regulation (EU) 2024/3015 on forced labour products', url: 'https://eur-lex.europa.eu/', organisation: 'EUR-Lex' },
    ],
    order: 3,
  },
  /* ---- EUROPEAN MEMBER STATES AND UK ---- */
  {
    name: 'German Supply Chain Act',
    shortName: 'LkSG',
    slug: 'german-supply-chain-act-lksg',
    jurisdiction: 'Germany',
    region: 'European Member States and UK',
    status: 'In force',
    statusType: 'force',
    lastUpdated: '2026-06-01',
    tableUpdateText: 'BAFA issues seventh enforcement action',
    enactedDate: 'June 2021 (in force January 2023)',
    firstComplianceDeadline: 'January 2023 (3,000+ employees); January 2024 (1,000+ employees)',
    companiesInScope: 'German companies with 1,000+ employees; foreign companies with a German branch of equivalent size',
    maxPenalty: '2% of annual global turnover for companies with EUR 400m+ turnover; up to EUR 800,000 for smaller companies; exclusion from public procurement for up to 3 years',
    civilLiability: 'No direct civil liability; enforcement through BAFA only',
    enforcementBody: 'Federal Office for Economic Affairs and Export Control (BAFA)',
    sectorsAffected: ['Textiles and apparel', 'Electronics', 'Automobiles', 'Agriculture and food', 'Mining'],
    supplierCountries: ['India', 'Bangladesh', 'Vietnam', 'China', 'Turkey', 'Morocco', 'Ghana', 'Brazil', 'Pakistan'],
    summary: [
      { type: 'paragraph', text: 'The German Supply Chain Due Diligence Act (Lieferkettensorgfaltspflichtengesetz, or LkSG) was the first major national supply chain due diligence law in Europe, entering into force in January 2023 for companies with 3,000 or more employees and expanding to companies with 1,000 or more employees in January 2024. It requires covered companies to conduct risk analyses, implement preventive and remediation measures, and establish grievance mechanisms across their direct and, to a more limited extent, indirect supply chains.' },
      { type: 'paragraph', text: 'Unlike the EU CSDDD, which will introduce civil liability, the LkSG operates through administrative enforcement only. The Federal Office for Economic Affairs and Export Control (BAFA) conducts audits, reviews company reports, and can issue fines and public procurement exclusions for non-compliance. As of June 2026, BAFA has issued seven formal enforcement actions, establishing important precedents for how the law will be applied in practice.' },
      { type: 'paragraph', text: 'For suppliers in the Global South, the practical consequence is a significant increase in documentation requests from German buyers. Suppliers who cannot demonstrate that their operations meet the LkSG risk standards are increasingly at risk of being cut from supply chains. The law does not require perfection, but it does require demonstrated effort, documented processes, and meaningful grievance mechanisms that workers can actually use.' },
    ],
    obligations: [
      { title: 'Annual risk analysis', detail: 'Companies must conduct a comprehensive risk analysis of their own operations, direct suppliers, and where there is substantiated knowledge of violations, their indirect supply chains.' },
      { title: 'Preventive measures', detail: 'Based on the risk analysis, companies must establish preventive measures including supplier codes of conduct, training, and contractual audit rights.' },
      { title: 'Grievance mechanism', detail: 'Companies must establish an accessible grievance mechanism that can receive complaints about human rights or environmental violations anywhere in their supply chain.' },
      { title: 'Remediation when violations occur', detail: 'When violations are identified, companies must develop and implement a remediation plan with a clear timeline and measurable outcomes.' },
      { title: 'Annual documentation and reporting', detail: 'Companies must document their due diligence efforts and publish an annual report on the BAFA platform.' },
    ],
    timeline: [
      { date: 'June 2021', event: 'LkSG enacted', detail: 'The German Bundestag passed the Lieferkettensorgfaltspflichtengesetz with a two-year implementation period.', isFuture: false },
      { date: 'January 2023', event: 'In force for 3,000+ employee companies', detail: 'Companies with 3,000 or more employees globally began legal obligations.', isFuture: false },
      { date: 'January 2024', event: 'Extended to 1,000+ employee companies', detail: 'Scope expanded to companies with 1,000 or more employees globally.', isFuture: false },
      { date: 'June 2026', event: 'Seventh BAFA enforcement action issued', detail: 'BAFA issued its seventh formal enforcement action under the law, marking a significant escalation in enforcement activity.', isFuture: false },
    ],
    changelog: [
      { date: '2026-06-01', summary: 'BAFA issues seventh enforcement action', detail: 'The Federal Office for Economic Affairs and Export Control issued a seventh formal enforcement action under the LkSG. While BAFA has not published the identity of the company under investigation, the enforcement letter relates to a failure to establish an adequate grievance mechanism accessible to workers in a direct suppliers operations in South Asia.' },
      { date: '2025-11-10', summary: 'BAFA publishes updated guidance on indirect supplier due diligence', detail: 'BAFA released an updated interpretation guide clarifying when companies are expected to conduct due diligence on indirect suppliers. The guidance specifies that substantiated knowledge of potential violations triggers an obligation to investigate, even in indirect supply chain tiers.' },
    ],
    sources: [
      { type: 'Official text', title: 'Lieferkettensorgfaltspflichtengesetz (LkSG)', url: 'https://www.gesetze-im-internet.de/lksg/', organisation: 'German Federal Government' },
      { type: 'Guidance', title: 'BAFA guidance documents and annual reports', url: 'https://www.bafa.de/EN/Foreign_Trade/Supply_Chain_Act/supply_chain_act_node.html', organisation: 'BAFA' },
    ],
    order: 4,
  },
  {
    name: 'French Duty of Vigilance Law',
    shortName: 'Loi de Vigilance',
    slug: 'french-duty-of-vigilance-law',
    jurisdiction: 'France',
    region: 'European Member States and UK',
    status: 'In force',
    statusType: 'force',
    lastUpdated: '2026-06-01',
    tableUpdateText: 'Court of Cassation upholds expanded interpretation',
    enactedDate: 'March 2017',
    firstComplianceDeadline: 'March 2018',
    companiesInScope: 'French companies with 5,000+ employees in France or 10,000+ worldwide',
    maxPenalty: 'No fixed amount; court can impose injunctions and damages',
    civilLiability: 'Yes, direct civil liability for damages caused by failure to exercise vigilance',
    enforcementBody: 'Courts (civil litigation model)',
    sectorsAffected: ['Oil and gas', 'Mining', 'Agribusiness', 'Retail', 'Construction'],
    supplierCountries: ['Senegal', 'Morocco', 'India', 'Brazil', 'Nigeria', 'Cameroon', 'Madagascar'],
    summary: [
      { type: 'paragraph', text: 'The French Duty of Vigilance Law (Loi relative au devoir de vigilance) was the first national law in Europe to require large companies to conduct due diligence across their supply chains and to create civil liability for failures of vigilance. Enacted in 2017, it established a model that has since influenced both the EU CSDDD and national legislation in Germany, Norway, and the Netherlands.' },
      { type: 'paragraph', text: 'The law requires covered French companies to publish and implement a "plan de vigilance" covering their own activities, subsidiaries, subcontractors, and suppliers with whom they have an established commercial relationship. The plan must identify serious risks to human rights, fundamental freedoms, health, safety, and the environment, and include specific measures to prevent and mitigate those risks.' },
      { type: 'paragraph', text: 'The distinctive feature of the French law is its civil liability provision: any person with a legitimate interest can bring a claim before a French court seeking damages if they can show that a company failed to fulfil its vigilance obligations and that this failure caused harm. Several cases are currently before French courts, with implications for how the law applies to global supply chains.' },
    ],
    obligations: [
      { title: 'Publish a vigilance plan', detail: 'Companies must publish an annual plan identifying risks and describing measures to identify and prevent serious violations of human rights and environmental standards.' },
      { title: 'Risk mapping', detail: 'The plan must include a risk map identifying and prioritising risks across operations, subsidiaries, and established commercial relationships.' },
      { title: 'Regular assessment procedures', detail: 'Companies must establish procedures to regularly assess subsidiaries, subcontractors, and suppliers with whom they have an established commercial relationship.' },
      { title: 'Appropriate actions to mitigate risks', detail: 'The plan must describe specific actions taken to mitigate identified risks across the supply chain.' },
      { title: 'Alert and monitoring mechanism', detail: 'Companies must implement an alert mechanism to collect reports from persons facing or witnessing serious violations, and a system to monitor its effectiveness.' },
    ],
    timeline: [
      { date: 'March 2017', event: 'Law enacted', detail: 'The Loi de Vigilance was promulgated after a lengthy legislative process.', isFuture: false },
      { date: 'March 2018', event: 'First vigilance plans due', detail: 'Covered companies published their first vigilance plans.', isFuture: false },
      { date: '2026-05', event: 'Court of Cassation ruling on expanded interpretation', detail: 'The Court of Cassation issued a significant ruling upholding an expanded interpretation of the established commercial relationship concept, potentially extending obligations to a broader set of supply chain relationships.', isFuture: false },
    ],
    changelog: [
      { date: '2026-05-20', summary: 'Court of Cassation upholds expanded interpretation of established commercial relationship', detail: 'The Court of Cassation upheld a lower court ruling that the concept of "established commercial relationship" under the Duty of Vigilance Law should be interpreted broadly to include indirect commercial relationships where the company exercises significant commercial influence. This ruling has significant implications for how far down supply chains French companies must exercise vigilance.' },
    ],
    sources: [
      { type: 'Official text', title: 'Loi no. 2017-399 relative au devoir de vigilance', url: 'https://www.legifrance.gouv.fr/', organisation: 'Legifrance' },
    ],
    order: 5,
  },
  {
    name: 'Norwegian Transparency Act',
    shortName: 'Apenhetsloven',
    slug: 'norwegian-transparency-act',
    jurisdiction: 'Norway',
    region: 'European Member States and UK',
    status: 'In force',
    statusType: 'force',
    lastUpdated: '2026-06-01',
    tableUpdateText: 'Third reporting cycle complete, 81 percent compliance',
    enactedDate: 'June 2021 (in force July 2022)',
    firstComplianceDeadline: 'July 2022',
    companiesInScope: 'Norwegian companies exceeding two of three thresholds: NOK 70m revenue, NOK 35m balance sheet, 50 employees; also applies to foreign companies marketing to Norwegian consumers',
    maxPenalty: 'Injunctions and fines for repeated or significant violations',
    civilLiability: 'Right to information; enforcement through Norwegian Consumer Authority',
    enforcementBody: 'Norwegian Consumer Authority (Forbrukertilsynet)',
    sectorsAffected: ['Consumer goods', 'Retail', 'Food and agriculture', 'Fashion and textiles'],
    supplierCountries: ['India', 'Bangladesh', 'China', 'Vietnam', 'Sri Lanka', 'Ethiopia', 'Kenya'],
    summary: [
      { type: 'paragraph', text: 'The Norwegian Transparency Act (Apenhetsloven) establishes obligations for larger Norwegian companies and foreign companies marketing to Norwegian consumers to conduct due diligence in their supply chains and to respond to public information requests. It is notable for its right-to-information provision, which allows any person to request information from a company about how it addresses human rights risks in its supply chain.' },
      { type: 'paragraph', text: 'The law requires covered companies to conduct due diligence based on the OECD Guidelines for Multinational Enterprises, to publish an annual due diligence report, and to respond within three weeks to information requests from the public or civil society organisations.' },
      { type: 'paragraph', text: 'The third annual reporting cycle, completed in spring 2026, showed 81 percent of covered companies had submitted compliant reports. The Consumer Authority has used enforcement actions to push companies toward more substantive rather than procedural compliance.' },
    ],
    obligations: [
      { title: 'Conduct OECD-based due diligence', detail: 'Companies must implement due diligence based on the OECD Guidelines for Multinational Enterprises.' },
      { title: 'Publish annual due diligence report', detail: 'Companies must publish a report on their due diligence, identifying the most salient human rights risks and what they are doing about them.' },
      { title: 'Respond to information requests', detail: 'Any person may request information about how the company handles human rights risks. The company must respond within three weeks.' },
    ],
    timeline: [
      { date: 'June 2021', event: 'Act enacted', detail: 'The Norwegian Parliament passed the Transparency Act.', isFuture: false },
      { date: 'July 2022', event: 'Act enters into force', detail: 'Obligations became enforceable.', isFuture: false },
      { date: 'Spring 2026', event: 'Third reporting cycle complete', detail: '81 percent of covered companies submitted compliant annual reports.', isFuture: false },
    ],
    changelog: [
      { date: '2026-05-15', summary: 'Third reporting cycle complete; 81 percent compliance rate reported', detail: 'The Norwegian Consumer Authority confirmed that 81 percent of companies required to report under the Transparency Act had submitted compliant annual reports for the third reporting cycle. The Authority noted continued concern about the depth of supply chain analysis in many reports, which identify risks at a generic level without specific findings or remediation actions.' },
    ],
    sources: [
      { type: 'Official text', title: 'Lov om virksomheters aapenhet og arbeid med grunnleggende menneskerettigheter og anstendige arbeidsforhold (apenhetsloven)', url: 'https://lovdata.no/', organisation: 'Lovdata' },
    ],
    order: 6,
  },
  {
    name: 'Dutch Child Labour Due Diligence Act',
    shortName: 'WKDD',
    slug: 'dutch-child-labour-due-diligence-act',
    jurisdiction: 'Netherlands',
    region: 'European Member States and UK',
    status: 'In force',
    statusType: 'force',
    lastUpdated: '2026-06-01',
    tableUpdateText: 'First public register of compliant companies released',
    enactedDate: 'May 2019 (in force January 2025)',
    firstComplianceDeadline: 'January 2025',
    companiesInScope: 'Companies selling goods or services to Dutch end users with turnover above EUR 3m',
    maxPenalty: 'EUR 870,000 or 10% of turnover for repeated violations; criminal liability for directors',
    civilLiability: 'No direct civil liability',
    enforcementBody: 'Authority for the Financial Markets (AFM)',
    sectorsAffected: ['Cocoa and chocolate', 'Coffee', 'Cotton and textiles', 'Electronics', 'Flowers', 'Tea'],
    supplierCountries: ['Ghana', 'Ivory Coast', 'Ethiopia', 'Kenya', 'Uganda', 'Tanzania', 'India', 'Bangladesh'],
    summary: [
      { type: 'paragraph', text: 'The Dutch Child Labour Due Diligence Act (Wet Zorgplicht Kinderarbeid) entered into force in January 2025 after a six-year delay. It requires companies selling goods or services to Dutch end users to conduct due diligence to determine whether their supply chains involve child labour. If a company identifies a reasonable suspicion of child labour, it must develop and implement an action plan to address it.' },
      { type: 'paragraph', text: 'The law covers companies with turnover above EUR 3 million that sell to Dutch consumers. Unlike laws focused only on large companies, this lower threshold makes it particularly relevant for mid-sized Dutch buyers in consumer goods supply chains.' },
      { type: 'paragraph', text: 'The Authority for the Financial Markets (AFM) maintains a public register of companies that have submitted the required declaration of compliance. Companies that have not submitted, or whose declarations are found to be inadequate, can face significant fines and, in repeated cases, criminal liability for directors.' },
    ],
    obligations: [
      { title: 'Submit declaration of due diligence', detail: 'Companies must submit a declaration to the AFM confirming they have conducted due diligence on child labour risks in their supply chains.' },
      { title: 'Develop action plan if risk found', detail: 'Where a reasonable suspicion of child labour is identified, companies must develop and implement a documented action plan.' },
      { title: 'Make declaration publicly available', detail: 'The declaration of due diligence must be publicly available on the company website.' },
    ],
    timeline: [
      { date: 'May 2019', event: 'Act enacted', detail: 'The Dutch Parliament passed the Child Labour Due Diligence Act.', isFuture: false },
      { date: 'January 2025', event: 'Act enters into force', detail: 'After several delays, the law became enforceable.', isFuture: false },
      { date: 'June 2026', event: 'First public register released', detail: 'AFM released the first public register of companies that have submitted compliant declarations.', isFuture: false },
    ],
    changelog: [
      { date: '2026-06-01', summary: 'First public register of compliant companies released by AFM', detail: 'The Authority for the Financial Markets published its first public register of companies that have submitted a declaration of compliance under the Child Labour Due Diligence Act. The register includes company names and a brief description of their due diligence approach. Companies not yet on the register have been notified and given a deadline to comply or face enforcement action.' },
    ],
    sources: [
      { type: 'Official text', title: 'Wet Zorgplicht Kinderarbeid', url: 'https://wetten.overheid.nl/', organisation: 'Dutch Government' },
    ],
    order: 7,
  },
  {
    name: 'UK Modern Slavery Act',
    shortName: 'UK MSA',
    slug: 'uk-modern-slavery-act',
    jurisdiction: 'United Kingdom',
    region: 'European Member States and UK',
    status: 'Updates pending',
    statusType: 'pending',
    lastUpdated: '2026-06-01',
    tableUpdateText: 'Mandatory due diligence amendment expected in autumn',
    enactedDate: 'March 2015',
    firstComplianceDeadline: 'September 2015',
    companiesInScope: 'Commercial organisations with annual turnover over GBP 36m operating in the UK',
    maxPenalty: 'Unlimited fines for failure to publish statement (once amendment passes)',
    civilLiability: 'None currently',
    enforcementBody: 'Home Office; proposed: Independent Anti-Slavery Commissioner with enforcement powers',
    sectorsAffected: ['Retail', 'Construction', 'Hospitality', 'Agriculture', 'Care sector'],
    supplierCountries: ['India', 'Bangladesh', 'Pakistan', 'Nepal', 'Vietnam', 'Nigeria', 'Ghana'],
    summary: [
      { type: 'paragraph', text: 'The UK Modern Slavery Act 2015 requires commercial organisations with turnover above GBP 36 million that supply goods or services in the UK to publish an annual transparency statement describing the steps they have taken to ensure their operations and supply chains are free from modern slavery and human trafficking. The law is widely acknowledged to have produced compliance that is more procedural than substantive.' },
      { type: 'paragraph', text: 'A mandatory due diligence amendment has been in the legislative pipeline since at least 2021, when a House of Lords bill proposed replacing the transparency statement requirement with a genuine due diligence obligation and introducing enforcement penalties. As of mid-2026, the amendment is expected to be introduced in the autumn legislative session.' },
      { type: 'paragraph', text: 'For Global South suppliers, the current law has limited direct practical effect, since its requirements fall on UK buyers rather than suppliers. The proposed amendment would change this by requiring UK buyers to actively identify and address supply chain risks, which would translate into due diligence requests and audits for their suppliers.' },
    ],
    obligations: [
      { title: 'Annual transparency statement', detail: 'Companies must publish an annual statement signed by a board director describing steps taken to ensure modern slavery is not occurring in operations or supply chains. Currently a disclosure requirement only, not a due diligence mandate.' },
      { title: 'Proposed: due diligence obligation', detail: 'If the pending amendment passes, companies will be required to conduct active due diligence, not merely report on their practices.' },
    ],
    timeline: [
      { date: 'March 2015', event: 'Act enacted', detail: 'The Modern Slavery Act received Royal Assent.', isFuture: false },
      { date: 'September 2015', event: 'Transparency statement requirement in force', detail: 'Companies above the turnover threshold began publishing annual statements.', isFuture: false },
      { date: 'Autumn 2026', event: 'Mandatory due diligence amendment expected', detail: 'The Government has indicated it will introduce legislation in the autumn 2026 session to add a mandatory due diligence requirement.', isFuture: true },
    ],
    changelog: [
      { date: '2026-04-10', summary: 'Government announces plan to introduce mandatory due diligence amendment in autumn 2026', detail: 'In a written statement to Parliament, the Home Secretary announced the Government plans to bring forward legislation in the autumn 2026 session to introduce mandatory due diligence requirements and meaningful penalties for non-compliance. Civil society organisations welcomed the announcement but called for the legislation to include civil liability provisions and to cover a broader range of harms beyond modern slavery.' },
    ],
    sources: [
      { type: 'Official text', title: 'Modern Slavery Act 2015', url: 'https://www.legislation.gov.uk/ukpga/2015/30/contents/enacted', organisation: 'UK Legislation' },
    ],
    order: 8,
  },
  {
    name: 'Swiss Responsible Business Ordinance',
    shortName: 'Swiss RBO',
    slug: 'swiss-responsible-business-ordinance',
    jurisdiction: 'Switzerland',
    region: 'European Member States and UK',
    status: 'Under review',
    statusType: 'proposed',
    lastUpdated: '2026-06-01',
    tableUpdateText: 'Federal Council reviewing scope expansion',
    enactedDate: 'January 2022',
    firstComplianceDeadline: 'January 2022',
    companiesInScope: 'Large Swiss companies in minerals from conflict areas and child labour risk supply chains',
    maxPenalty: 'Administrative fines',
    civilLiability: 'No',
    enforcementBody: 'Federal authorities',
    sectorsAffected: ['Minerals and metals', 'Cocoa', 'Coffee', 'Textiles'],
    supplierCountries: ['Democratic Republic of Congo', 'Nigeria', 'Ghana', 'Ethiopia', 'India', 'Bangladesh'],
    summary: [
      { type: 'paragraph', text: 'The Swiss Responsible Business Ordinance (Verordnung uber Sorgfaltspflichten und Transparenz bezuglich Mineralien und Metallen aus Konfliktgebieten und Kindheitsarbeit) entered into force in January 2022. It is narrower in scope than comparable EU legislation, applying only to supply chain due diligence for minerals and metals from conflict-affected areas and for supply chains with child labour risks.' },
      { type: 'paragraph', text: 'The ordinance was issued under the Swiss Code of Obligations following the rejection of the Responsible Business Initiative in a 2020 referendum. The Federal Council is now reviewing whether to expand the scope of the ordinance to align more closely with the EU CSDDD as Switzerland seeks to maintain regulatory coherence with its major trading partners.' },
      { type: 'paragraph', text: 'For suppliers in affected sectors, the ordinance requires Swiss buyers to conduct due diligence on minerals and metals from conflict zones and on supply chains with identified child labour risks. An expansion of scope would significantly increase the obligations on Swiss companies and correspondingly on their Global South suppliers.' },
    ],
    obligations: [
      { title: 'Supply chain due diligence for conflict minerals', detail: 'Companies importing tin, tantalum, tungsten, or gold from conflict-affected areas must conduct due diligence in line with OECD guidance.' },
      { title: 'Supply chain due diligence for child labour', detail: 'Companies with supply chains in countries with elevated child labour risks must conduct due diligence to identify and address child labour.' },
      { title: 'Annual reporting', detail: 'Covered companies must publish an annual due diligence report on their supply chain practices.' },
    ],
    timeline: [
      { date: 'November 2020', event: 'Responsible Business Initiative rejected in referendum', detail: 'The broader initiative to create civil liability for Swiss companies was rejected by 50.7% of voters.', isFuture: false },
      { date: 'January 2022', event: 'Ordinance enters into force', detail: 'The narrower ordinance covering conflict minerals and child labour entered into force.', isFuture: false },
      { date: '2026 (ongoing)', event: 'Federal Council reviewing scope expansion', detail: 'The Federal Council is evaluating whether to expand the scope to align with EU CSDDD.', isFuture: true },
    ],
    changelog: [
      { date: '2026-03-01', summary: 'Federal Council begins formal review of scope expansion', detail: 'The Swiss Federal Council announced a formal review process to evaluate whether the Responsible Business Ordinance should be expanded to cover a broader range of human rights and environmental risks, in line with the EU CSDDD. A consultation period is expected to open in late 2026.' },
    ],
    sources: [
      { type: 'Official text', title: 'Swiss Responsible Business Ordinance (SR 221.331)', url: 'https://www.fedlex.admin.ch/', organisation: 'Swiss Federal Chancellery' },
    ],
    order: 9,
  },
  /* ---- NORTH AMERICA ---- */
  {
    name: 'Uyghur Forced Labor Prevention Act',
    shortName: 'US UFLPA',
    slug: 'us-uflpa',
    jurisdiction: 'United States',
    region: 'North America',
    status: 'In force',
    statusType: 'force',
    lastUpdated: '2026-06-01',
    tableUpdateText: 'CBP entity list expanded by 23 new companies',
    enactedDate: 'December 2021 (in force June 2022)',
    firstComplianceDeadline: 'June 2022',
    companiesInScope: 'Any importer of goods into the United States',
    maxPenalty: 'Detention and seizure of goods; civil penalties',
    civilLiability: 'No',
    enforcementBody: 'Customs and Border Protection (CBP)',
    sectorsAffected: ['Cotton and textiles', 'Polysilicon and solar', 'Tomatoes', 'Electronics components'],
    supplierCountries: ['China (Xinjiang region specifically)'],
    summary: [
      { type: 'paragraph', text: 'The Uyghur Forced Labor Prevention Act (UFLPA) creates a rebuttable presumption that any goods produced wholly or in part in the Xinjiang Uyghur Autonomous Region of China were made with forced labour and are therefore prohibited from import into the United States. This presumption can only be rebutted by clear and convincing evidence to the contrary, a very high standard that few importers have successfully met.' },
      { type: 'paragraph', text: 'The law operates through the US Customs and Border Protection (CBP), which maintains an entity list of companies operating in Xinjiang that are subject to enhanced scrutiny. As of June 2026, the entity list has been expanded by 23 new companies, bringing the total to well over 100 entities. Goods connected to any entity list company face near-automatic detention at the US border.' },
      { type: 'paragraph', text: 'While the UFLPA is specifically targeted at Xinjiang, its indirect effects extend beyond China. Global supply chains for cotton, polysilicon, and electronics components have been significantly disrupted, creating both risks and opportunities for alternative suppliers in South and Southeast Asia.' },
    ],
    obligations: [
      { title: 'Supply chain traceability for Xinjiang connections', detail: 'Importers with any potential connection to Xinjiang must be able to trace their supply chains and demonstrate that no goods were produced with forced labour.' },
      { title: 'Rebut presumption to import detained goods', detail: 'If goods are detained, importers must provide clear and convincing evidence to CBP that the goods were not produced with forced labour.' },
      { title: 'Monitor entity list', detail: 'Importers should regularly monitor the CBP entity list and ensure their supply chains do not connect to listed entities.' },
    ],
    timeline: [
      { date: 'December 2021', event: 'UFLPA enacted', detail: 'Signed into law with a six-month implementation period.', isFuture: false },
      { date: 'June 2022', event: 'UFLPA enforcement begins', detail: 'CBP began enforcing the rebuttable presumption and maintaining the entity list.', isFuture: false },
      { date: 'June 2026', event: 'Entity list expanded by 23 companies', detail: 'CBP announced the addition of 23 new companies to the UFLPA entity list.', isFuture: false },
    ],
    changelog: [
      { date: '2026-06-01', summary: 'CBP entity list expanded by 23 new companies', detail: 'US Customs and Border Protection announced the addition of 23 new companies to the UFLPA Entity List. The new additions include companies in cotton ginning, polysilicon manufacturing, and electronic components. Importers connected to any of these entities face automatic detention of goods at the US border.' },
    ],
    sources: [
      { type: 'Official text', title: 'Uyghur Forced Labor Prevention Act (PL 117-78)', url: 'https://www.congress.gov/', organisation: 'US Congress' },
      { type: 'Guidance', title: 'UFLPA Entity List', url: 'https://www.cbp.gov/', organisation: 'US Customs and Border Protection' },
    ],
    order: 10,
  },
  {
    name: 'California Climate Corporate Data Accountability and Accountability Acts',
    shortName: 'California SB 253 / SB 261',
    slug: 'california-sb-253-261',
    jurisdiction: 'California, USA',
    region: 'North America',
    status: 'Implementing',
    statusType: 'pending',
    lastUpdated: '2026-06-01',
    tableUpdateText: 'CARB releases final rulemaking, first reports due January 2027',
    enactedDate: 'October 2023',
    firstComplianceDeadline: 'January 2027 (Scope 1 and 2 emissions reporting)',
    companiesInScope: 'SB 253: US companies with revenues over USD 1bn doing business in California; SB 261: US companies with revenues over USD 500m doing business in California',
    maxPenalty: 'USD 500,000 per year per violation',
    civilLiability: 'No direct civil liability',
    enforcementBody: 'California Air Resources Board (CARB)',
    sectorsAffected: ['All sectors with operations in California', 'Retail', 'Technology', 'Manufacturing'],
    supplierCountries: ['China', 'India', 'Vietnam', 'Mexico', 'Bangladesh', 'Indonesia'],
    summary: [
      { type: 'paragraph', text: 'California Senate Bills 253 and 261 together create the most comprehensive corporate climate disclosure regime in the United States. SB 253 requires large companies doing business in California to disclose their greenhouse gas emissions across all three scopes, including their supply chain emissions (Scope 3). SB 261 requires separate disclosure of climate-related financial risks. Together, they affect thousands of US companies and, through supply chain reporting requirements, their global suppliers.' },
      { type: 'paragraph', text: 'The California Air Resources Board released its final rulemaking in early 2026, and first reports are due in January 2027. The Scope 3 supply chain emissions disclosure requirement is of particular relevance for Global South suppliers, as buyers subject to the law will need to collect emissions data from their suppliers to fulfil their reporting obligations.' },
      { type: 'paragraph', text: 'While not an HREDD law in the traditional sense, the supply chain data requirements of SB 253 are creating significant new information demands on Global South suppliers. Companies that cannot provide verifiable emissions data may find themselves disadvantaged in relationships with California-based buyers.' },
    ],
    obligations: [
      { title: 'Scope 1 and 2 emissions disclosure (SB 253)', detail: 'Annual disclosure of direct and indirect energy-related emissions from operations.' },
      { title: 'Scope 3 emissions disclosure (SB 253)', detail: 'Annual disclosure of supply chain and value chain emissions, with a one-year delayed timeline from Scopes 1 and 2.' },
      { title: 'Climate risk disclosure (SB 261)', detail: 'Biennial disclosure of climate-related financial risks and mitigation strategies, aligned with TCFD framework.' },
    ],
    timeline: [
      { date: 'October 2023', event: 'Bills signed into law', detail: 'Governor Newsom signed both SB 253 and SB 261 into law.', isFuture: false },
      { date: 'Early 2026', event: 'CARB final rulemaking released', detail: 'California Air Resources Board published its final rulemaking clarifying reporting requirements.', isFuture: false },
      { date: 'January 2027', event: 'First Scope 1 and 2 reports due', detail: 'Companies must submit their first reports on direct emissions.', isFuture: true },
      { date: 'January 2028', event: 'First Scope 3 reports due', detail: 'Supply chain emissions reporting begins.', isFuture: true },
    ],
    changelog: [
      { date: '2026-03-15', summary: 'CARB releases final rulemaking for SB 253 implementation', detail: 'The California Air Resources Board published final rulemaking guidance on how companies should calculate and report Scope 1, 2, and 3 emissions. The guidance aligns broadly with the GHG Protocol Corporate Standard and allows companies to use existing third-party standards for Scope 3 category calculations.' },
    ],
    sources: [
      { type: 'Official text', title: 'California SB 253 (Climate Corporate Data Accountability Act)', url: 'https://leginfo.legislature.ca.gov/', organisation: 'California Legislature' },
    ],
    order: 11,
  },
  {
    name: 'Canada Fighting Against Forced Labour and Child Labour in Supply Chains Act',
    shortName: 'Canada FLCCA',
    slug: 'canada-flcca',
    jurisdiction: 'Canada',
    region: 'North America',
    status: 'In force',
    statusType: 'force',
    lastUpdated: '2026-06-01',
    tableUpdateText: 'Second annual reporting cycle open, 68 percent first-year compliance',
    enactedDate: 'May 2023 (in force January 2024)',
    firstComplianceDeadline: 'May 2024 (first reports)',
    companiesInScope: 'Government institutions and entities listed on a Canadian stock exchange meeting size thresholds; also entities producing, selling, or distributing goods in Canada or importing goods into Canada meeting size thresholds',
    maxPenalty: 'Up to CAD 250,000 per violation',
    civilLiability: 'No',
    enforcementBody: 'Minister of Public Safety',
    sectorsAffected: ['Retail', 'Mining', 'Agri-food', 'Apparel', 'Electronics'],
    supplierCountries: ['India', 'Bangladesh', 'Vietnam', 'China', 'Mexico', 'Ghana', 'Peru'],
    summary: [
      { type: 'paragraph', text: 'The Canada Fighting Against Forced Labour and Child Labour in Supply Chains Act came into force in January 2024, making Canada the first country outside Europe to enact a mandatory supply chain transparency law covering both forced labour and child labour. It requires covered government institutions and private entities to report annually on the steps they have taken to prevent and reduce the risk of forced or child labour in their supply chains.' },
      { type: 'paragraph', text: 'The first reporting cycle, completed in May 2025, saw 68 percent of covered entities submit compliant reports. The second cycle opened in January 2026. The Minister of Public Safety has indicated that non-reporters and entities with inadequate reports will face escalating scrutiny in the second cycle.' },
      { type: 'paragraph', text: 'The law is currently under review with amendments expected that would introduce more substantive due diligence requirements, moving beyond transparency reporting toward the model established by German and EU legislation. In the meantime, it is creating new information demands on Canadian importers and, consequently, on their global suppliers.' },
    ],
    obligations: [
      { title: 'Annual report on supply chain practices', detail: 'Covered entities must submit an annual report to the Minister describing their supply chains, policies on forced and child labour, due diligence processes, and training provided.' },
      { title: 'Make report publicly available', detail: 'The report must be published on the entity website and submitted to the government within six months of the financial year end.' },
    ],
    timeline: [
      { date: 'May 2023', event: 'Act enacted', detail: 'The Canadian Parliament passed the Fighting Against Forced Labour and Child Labour in Supply Chains Act.', isFuture: false },
      { date: 'January 2024', event: 'Act enters into force', detail: 'Obligations became enforceable for covered entities.', isFuture: false },
      { date: 'May 2025', event: 'First reporting cycle complete', detail: '68 percent of covered entities submitted compliant reports.', isFuture: false },
      { date: 'January 2026', event: 'Second annual reporting cycle opens', detail: 'The second reporting cycle is now open.', isFuture: false },
    ],
    changelog: [
      { date: '2026-01-15', summary: 'Second annual reporting cycle opens; amendments under discussion', detail: 'The second annual reporting cycle opened on 1 January 2026. Simultaneously, the Canadian government announced a public consultation on proposed amendments to the law that would introduce more substantive due diligence requirements beyond transparency reporting, moving toward alignment with the EU CSDDD model.' },
    ],
    sources: [
      { type: 'Official text', title: 'Fighting Against Forced Labour and Child Labour in Supply Chains Act (S-211)', url: 'https://laws-lois.justice.gc.ca/', organisation: 'Government of Canada' },
    ],
    order: 12,
  },
  /* ---- ASIA-PACIFIC ---- */
  {
    name: 'Australia Modern Slavery Act',
    shortName: 'Australia MSA',
    slug: 'australia-modern-slavery-act',
    jurisdiction: 'Australia',
    region: 'Asia-Pacific',
    status: 'Reform proposed',
    statusType: 'pending',
    lastUpdated: '2026-06-01',
    tableUpdateText: 'Independent review recommends mandatory due diligence and penalties',
    enactedDate: 'November 2018 (in force January 2019)',
    firstComplianceDeadline: 'December 2019',
    companiesInScope: 'Australian entities and foreign entities with annual consolidated revenue over AUD 100m that carry on business in Australia',
    maxPenalty: 'None currently; proposed amendments include significant penalties',
    civilLiability: 'None currently',
    enforcementBody: 'Department of Home Affairs (reporting); proposed: new enforcement body with penalties',
    sectorsAffected: ['Retail', 'Construction', 'Agriculture', 'Manufacturing', 'Finance'],
    supplierCountries: ['India', 'Bangladesh', 'Vietnam', 'China', 'Indonesia', 'Philippines', 'Myanmar'],
    summary: [
      { type: 'paragraph', text: 'The Australian Modern Slavery Act 2018 requires entities with annual consolidated revenue over AUD 100 million that carry on business in Australia to report annually on modern slavery risks in their operations and supply chains. The law is broadly similar to the UK Modern Slavery Act in requiring transparency statements rather than active due diligence, and has attracted similar criticism for producing compliance that is more procedural than substantive.' },
      { type: 'paragraph', text: 'An independent review of the Act published in 2023 recommended significant reforms, including the introduction of mandatory due diligence obligations, a due diligence standard aligned with the UN Guiding Principles, enforcement penalties for non-compliance, and the lowering of the revenue threshold to capture more companies. As of mid-2026, the government is considering which recommendations to implement.' },
      { type: 'paragraph', text: 'For suppliers in the Pacific region and South and Southeast Asia, the proposed reforms would substantially increase the compliance burden on Australian buyers and translate into meaningful due diligence activity across their supply chains. The timing of any reforms, however, remains uncertain.' },
    ],
    obligations: [
      { title: 'Annual modern slavery statement', detail: 'Covered entities must prepare a statement addressing the seven mandatory criteria set out in the Act, including supply chain risk assessment and due diligence processes.' },
      { title: 'Proposed: mandatory due diligence', detail: 'The independent review recommends replacing the transparency statement with a genuine due diligence obligation. Not yet law.' },
    ],
    timeline: [
      { date: 'November 2018', event: 'Act enacted', detail: 'The Modern Slavery Act 2018 received Royal Assent.', isFuture: false },
      { date: 'January 2019', event: 'Act enters into force', detail: 'Reporting obligations became active.', isFuture: false },
      { date: '2023', event: 'Independent review published', detail: 'The Statutory Review recommended significant reforms including mandatory due diligence and penalties.', isFuture: false },
      { date: '2026 (ongoing)', event: 'Government response to review awaited', detail: 'The government is considering which review recommendations to implement.', isFuture: true },
    ],
    changelog: [
      { date: '2026-04-01', summary: 'Government signals support for mandatory due diligence and penalties', detail: 'The Australian Government indicated in a Senate committee hearing that it intends to bring forward legislation implementing the core recommendations of the independent review, including mandatory due diligence and financial penalties for non-compliance. Draft legislation is expected by the end of 2026.' },
    ],
    sources: [
      { type: 'Official text', title: 'Modern Slavery Act 2018', url: 'https://www.legislation.gov.au/', organisation: 'Australian Government' },
    ],
    order: 13,
  },
  {
    name: 'Japan Human Rights Due Diligence Guidelines',
    shortName: 'Japan HRDD Guidelines',
    slug: 'japan-hrdd-guidelines',
    jurisdiction: 'Japan',
    region: 'Asia-Pacific',
    status: 'Voluntary',
    statusType: 'proposed',
    lastUpdated: '2026-06-01',
    tableUpdateText: 'METI considers conversion to mandatory framework',
    enactedDate: 'September 2022 (guidelines published)',
    firstComplianceDeadline: 'N/A (voluntary)',
    companiesInScope: 'All Japanese companies (voluntary encouragement)',
    maxPenalty: 'N/A',
    civilLiability: 'N/A',
    enforcementBody: 'Ministry of Economy, Trade and Industry (METI)',
    sectorsAffected: ['Electronics', 'Automotive', 'Retail', 'Food and agriculture'],
    supplierCountries: ['China', 'Vietnam', 'Thailand', 'India', 'Bangladesh', 'Indonesia'],
    summary: [
      { type: 'paragraph', text: 'Japan published non-binding guidelines on human rights due diligence for businesses in September 2022, following the adoption of the UN Guiding Principles on Business and Human Rights. The guidelines encourage Japanese companies to conduct human rights due diligence across their value chains but stop short of creating legal obligations.' },
      { type: 'paragraph', text: 'The Ministry of Economy, Trade and Industry (METI) has been monitoring corporate uptake of the guidelines and is now considering whether to convert them into a mandatory framework, in response to pressure from the EU to harmonise standards as part of bilateral trade negotiations.' },
      { type: 'paragraph', text: 'For suppliers in Southeast and South Asia, the Japanese market is significant. A mandatory HRDD framework in Japan would create new compliance demands on suppliers to Japanese companies. The timeline for any mandatory framework, however, remains uncertain.' },
    ],
    obligations: [
      { title: 'Voluntary human rights due diligence', detail: 'Japanese companies are encouraged, but not required, to conduct due diligence following the UN Guiding Principles model.' },
    ],
    timeline: [
      { date: 'September 2022', event: 'Guidelines published', detail: 'METI published voluntary human rights due diligence guidelines.', isFuture: false },
      { date: '2026 (ongoing)', event: 'METI reviewing mandatory framework', detail: 'Government considering legislation to make guidelines mandatory.', isFuture: true },
    ],
    changelog: [
      { date: '2026-05-01', summary: 'METI announces review process for mandatory HRDD framework', detail: 'The Japanese Ministry of Economy, Trade and Industry formally announced a stakeholder review process to evaluate converting the voluntary HRDD guidelines into a mandatory framework. The review is expected to conclude by the end of 2026, with any legislative proposal following in 2027.' },
    ],
    sources: [
      { type: 'Guidance', title: 'Guidelines on Respecting Human Rights in Responsible Supply Chains', url: 'https://www.meti.go.jp/', organisation: 'METI' },
    ],
    order: 14,
  },
  {
    name: 'South Korea Business and Human Rights Act',
    shortName: 'South Korea BHR Act',
    slug: 'south-korea-business-and-human-rights-act',
    jurisdiction: 'South Korea',
    region: 'Asia-Pacific',
    status: 'In committee',
    statusType: 'proposed',
    lastUpdated: '2026-06-01',
    tableUpdateText: 'Bill advances to National Assembly committee review',
    enactedDate: 'Not yet enacted',
    firstComplianceDeadline: 'N/A',
    companiesInScope: 'Proposed: companies with 500+ employees or KRW 30bn+ revenue',
    maxPenalty: 'Proposed: fines and public naming',
    civilLiability: 'Not in current draft',
    enforcementBody: 'Proposed: Ministry of Trade, Industry and Energy',
    sectorsAffected: ['Electronics', 'Automotive', 'Steel', 'Shipbuilding', 'Chemicals'],
    supplierCountries: ['Vietnam', 'Philippines', 'Bangladesh', 'Cambodia', 'Indonesia'],
    summary: [
      { type: 'paragraph', text: 'South Korea has been developing national legislation on business and human rights since 2021, when the government published a National Action Plan. A formal draft bill has now advanced to committee review in the National Assembly, marking the most significant legislative progress to date.' },
      { type: 'paragraph', text: 'The proposed law would require companies meeting size thresholds to conduct due diligence on human rights and environmental risks in their operations and supply chains, publish annual reports, and establish grievance mechanisms. The draft follows the UN Guiding Principles framework and takes significant inspiration from the German LkSG.' },
      { type: 'paragraph', text: 'South Korea is a major buyer of garments, electronics components, and agricultural commodities from South and Southeast Asia. A mandatory HRDD law would create significant new compliance demands on suppliers to Korean companies, particularly in the electronics and apparel sectors.' },
    ],
    obligations: [
      { title: 'Human rights due diligence (proposed)', detail: 'Covered companies would be required to identify, prevent, and address human rights and environmental risks across their supply chains.' },
      { title: 'Annual reporting (proposed)', detail: 'Companies would need to publish annual due diligence reports.' },
      { title: 'Grievance mechanism (proposed)', detail: 'Companies would need to establish accessible grievance mechanisms for workers in their supply chains.' },
    ],
    timeline: [
      { date: '2021', event: 'National Action Plan published', detail: 'South Korean government published its National Action Plan on Business and Human Rights, committing to develop legislation.', isFuture: false },
      { date: '2025', event: 'Draft bill introduced to National Assembly', detail: 'A formal draft bill was introduced for legislative consideration.', isFuture: false },
      { date: 'June 2026', event: 'Bill advances to committee review', detail: 'The National Assembly committee on trade and industry began formal review of the bill.', isFuture: false },
      { date: '2027 (projected)', event: 'Potential enactment', detail: 'If the committee process proceeds without significant delay, the bill could be enacted in 2027.', isFuture: true },
    ],
    changelog: [
      { date: '2026-06-01', summary: 'National Assembly committee begins formal review of Business and Human Rights Act', detail: 'The National Assembly Standing Committee on Trade, Industry and Energy began formal review of the Business and Human Rights Act bill. Stakeholder hearings are scheduled for August and September 2026. Business associations have raised concerns about compliance costs; civil society organisations have called for stronger civil liability provisions.' },
    ],
    sources: [
      { type: 'Analysis', title: 'South Korea National Action Plan on Business and Human Rights', url: 'https://www.mohw.go.kr/', organisation: 'Ministry of Health and Welfare' },
    ],
    order: 15,
  },
  /* ---- GLOBAL SOUTH ---- */
  {
    name: 'India Business Responsibility and Sustainability Report Core',
    shortName: 'India BRSR Core',
    slug: 'india-brsr-core',
    jurisdiction: 'India',
    region: 'Global South',
    status: 'Expanding',
    statusType: 'pending',
    lastUpdated: '2026-06-01',
    tableUpdateText: 'SEBI extends mandatory disclosure to top 500 listed companies',
    enactedDate: 'February 2023 (BRSR Core mandatory for top 150 listed companies)',
    firstComplianceDeadline: 'FY 2023-24 (top 150 listed companies)',
    companiesInScope: 'Now expanding to top 500 NSE/BSE listed companies',
    maxPenalty: 'SEBI enforcement under Securities regulations',
    civilLiability: 'No',
    enforcementBody: 'Securities and Exchange Board of India (SEBI)',
    sectorsAffected: ['All sectors listed on NSE/BSE', 'Particularly: textiles, mining, agri-food, pharma'],
    supplierCountries: ['India (domestic supply chains)'],
    summary: [
      { type: 'paragraph', text: 'The Business Responsibility and Sustainability Report (BRSR) Core is a framework issued by the Securities and Exchange Board of India requiring large listed companies to make mandatory disclosures on environmental, social, and governance performance. The Core section of the BRSR focuses on nine key performance indicators across human rights, labour standards, and environmental practices, with assured (third-party verified) reporting required from the top listed companies.' },
      { type: 'paragraph', text: 'When first introduced as mandatory in FY 2023-24, the BRSR Core applied to the top 150 NSE and BSE listed companies. SEBI has now extended the mandatory requirement to the top 500 listed companies, significantly expanding the number of Indian businesses subject to assured ESG disclosure. The extension represents a significant step toward supply chain accountability within India itself.' },
      { type: 'paragraph', text: 'The BRSR Core is notable as a Global South example of a home country requiring its own large companies to be accountable for supply chain practices, rather than being regulated solely by requirements imposed from importing countries. For smaller suppliers within Indian supply chains, this creates new documentation expectations from their domestic buyers.' },
    ],
    obligations: [
      { title: 'Nine key performance indicator disclosures', detail: 'Covered companies must report with third-party assurance on nine specified KPIs covering environmental, social, and governance matters.' },
      { title: 'Supply chain disclosures', detail: 'Several KPIs require disclosure on supply chain practices, including working conditions and environmental impacts at supplier level.' },
      { title: 'Third-party assurance', detail: 'Unlike voluntary BRSR disclosures, the Core section requires reasonable or limited assurance from an independent third party.' },
    ],
    timeline: [
      { date: 'February 2023', event: 'BRSR Core made mandatory for top 150 listed companies', detail: 'SEBI circular issued making BRSR Core disclosures mandatory for FY 2023-24 onwards for the top 150 companies by market capitalisation.', isFuture: false },
      { date: 'FY 2024-25', event: 'First reports for top 150 companies published', detail: 'Companies submitted their first BRSR Core reports with third-party assurance.', isFuture: false },
      { date: 'June 2026', event: 'Expansion to top 500 announced', detail: 'SEBI announced extension of mandatory BRSR Core to the top 500 listed companies from FY 2025-26.', isFuture: false },
    ],
    changelog: [
      { date: '2026-06-01', summary: 'SEBI extends BRSR Core obligation to top 500 listed companies', detail: 'The Securities and Exchange Board of India issued a circular extending the mandatory BRSR Core disclosure requirement from the top 150 to the top 500 NSE and BSE listed companies, effective from the financial year 2025-26. The move significantly increases the number of Indian companies subject to assured ESG disclosure and has implications for their supply chain documentation requirements.' },
    ],
    sources: [
      { type: 'Guidance', title: 'SEBI Circular on BRSR Core', url: 'https://www.sebi.gov.in/', organisation: 'Securities and Exchange Board of India' },
    ],
    order: 16,
  },
  {
    name: 'Brazil Supply Chain Due Diligence Bill',
    shortName: 'Brazil DD Bill',
    slug: 'brazil-supply-chain-due-diligence-bill',
    jurisdiction: 'Brazil',
    region: 'Global South',
    status: 'In Congress',
    statusType: 'pending',
    lastUpdated: '2026-06-01',
    tableUpdateText: 'Bill PL 572 advances through environmental committee',
    enactedDate: 'Not yet enacted',
    firstComplianceDeadline: 'N/A',
    companiesInScope: 'Proposed: Brazilian companies with annual revenue above BRL 300m',
    maxPenalty: 'Proposed: fines up to 2% of annual Brazilian revenue',
    civilLiability: 'Proposed: yes',
    enforcementBody: 'Proposed: Ministry of Justice and federal courts',
    sectorsAffected: ['Agribusiness', 'Mining', 'Retail', 'Manufacturing', 'Finance'],
    supplierCountries: ['Brazil (domestic supply chains)', 'with significant implications for domestic agricultural suppliers'],
    summary: [
      { type: 'paragraph', text: 'Brazil is one of the few countries in the Global South developing its own supply chain due diligence legislation. Bill PL 572/2022 proposes to require large Brazilian companies to conduct human rights and environmental due diligence across their domestic and international supply chains. The bill explicitly draws on the French Duty of Vigilance Law and the UN Guiding Principles on Business and Human Rights.' },
      { type: 'paragraph', text: 'The bill has advanced through several committees in the Brazilian Chamber of Deputies and has now moved to the Environmental Committee. Passage remains uncertain given the complexity of the legislative environment, but the bill has significant civil society support and the attention of major Brazilian business associations who are watching European developments closely.' },
      { type: 'paragraph', text: 'If enacted, a Brazilian due diligence law would be a landmark development, representing one of the first comprehensive HREDD frameworks in the Global South. It would also create new obligations on Brazilian companies operating in other developing countries, affecting supply chains across Latin America and parts of Africa.' },
    ],
    obligations: [
      { title: 'Human rights and environmental due diligence (proposed)', detail: 'Large Brazilian companies would be required to conduct due diligence on human rights and environmental risks in their operations and supply chains.' },
      { title: 'Vigilance plan (proposed)', detail: 'Companies would need to publish and implement a vigilance plan, modelled on the French Duty of Vigilance approach.' },
      { title: 'Civil liability for harm (proposed)', detail: 'Companies that fail to exercise adequate vigilance and cause harm could face civil liability under the proposed law.' },
    ],
    timeline: [
      { date: '2022', event: 'Bill PL 572 introduced', detail: 'The bill was introduced in the Brazilian Chamber of Deputies.', isFuture: false },
      { date: 'May 2026', event: 'Bill advances to Environmental Committee', detail: 'After clearing the Human Rights Committee, the bill moved to the Environmental Committee for review.', isFuture: false },
      { date: '2027 (projected)', event: 'Potential floor vote', detail: 'If committee review proceeds without major delays, a floor vote could occur in 2027.', isFuture: true },
    ],
    changelog: [
      { date: '2026-05-20', summary: 'Bill PL 572 advances to Environmental Committee after Human Rights Committee approval', detail: 'The Brazilian Chamber of Deputies Human Rights Committee approved Bill PL 572 with amendments strengthening the civil liability provisions and expanding the definition of covered supply chain relationships. The bill now moves to the Environmental Committee before it can proceed to a full chamber vote.' },
    ],
    sources: [
      { type: 'Official text', title: 'Bill PL 572/2022 (full text in Portuguese)', url: 'https://www.camara.leg.br/', organisation: 'Brazilian Chamber of Deputies' },
    ],
    order: 17,
  },
  {
    name: 'Mexico Labour Reform (USMCA-linked)',
    shortName: 'Mexico Labour Reform',
    slug: 'mexico-labour-reform',
    jurisdiction: 'Mexico',
    region: 'Global South',
    status: 'In force',
    statusType: 'force',
    lastUpdated: '2026-06-01',
    tableUpdateText: 'USMCA Rapid Response Mechanism invoked in two new cases',
    enactedDate: 'May 2019 (labour reform); July 2020 (USMCA Rapid Response operational)',
    firstComplianceDeadline: 'May 2023 (full union democracy reform deadline)',
    companiesInScope: 'Manufacturing and export facilities in Mexico, particularly in automotive, apparel, and agribusiness sectors',
    maxPenalty: 'USMCA trade enforcement measures; suspension of preferential tariffs on specific goods',
    civilLiability: 'No',
    enforcementBody: 'US Trade Representative and Mexican STPS under USMCA Rapid Response Mechanism',
    sectorsAffected: ['Automotive', 'Electronics', 'Apparel', 'Agribusiness', 'Mining'],
    supplierCountries: ['Mexico is a supplier country in this context; labour reform affects domestic workforce'],
    summary: [
      { type: 'paragraph', text: 'Mexico implemented significant labour law reforms in 2019, including a shift to union democracy, direct collective bargaining agreements, and independent labour courts. These reforms were a condition of the United States-Mexico-Canada Agreement (USMCA), which also introduced the Rapid Response Mechanism (RRM), allowing the US and Canada to request expedited review of labour rights violations at specific Mexican facilities.' },
      { type: 'paragraph', text: 'The USMCA Rapid Response Mechanism is significant because it creates a direct link between labour conditions at specific Mexican production facilities and trade access. Where the RRM finds that workers are being denied rights under Mexican law, the US and Canada can impose remediation requirements and, if these are not met, suspend preferential tariff treatment on goods from that facility.' },
      { type: 'paragraph', text: 'As of June 2026, the Rapid Response Mechanism has been invoked in two new cases, bringing the total number of RRM petitions filed since 2020 to over thirty. The mechanism has become a significant enforcement tool for labour rights in Mexican export sectors and a useful case study in how trade-linked labour enforcement can create real consequences for specific facilities.' },
    ],
    obligations: [
      { title: 'Genuine union representation', detail: 'Mexican manufacturing facilities must allow genuine union elections and collective bargaining under the reformed legal framework.' },
      { title: 'Comply with RRM remediation requirements', detail: 'Facilities subject to RRM investigations must remediate identified violations within the timeframe set by the panel, or face suspension of tariff benefits.' },
      { title: 'Freedom of association', detail: 'Workers must be able to freely organise and join unions of their choosing without employer interference.' },
    ],
    timeline: [
      { date: 'May 2019', event: 'Labour reform enacted', detail: 'Mexico enacted comprehensive labour law reforms as part of USMCA negotiations.', isFuture: false },
      { date: 'July 2020', event: 'USMCA enters into force; RRM becomes operational', detail: 'The Rapid Response Mechanism for labour rights enforcement became active.', isFuture: false },
      { date: 'May 2023', event: 'Full union democracy reform deadline', detail: 'All pre-reform collective agreements had to be re-voted under new rules.', isFuture: false },
      { date: 'June 2026', event: 'RRM invoked in two new cases', detail: 'Two new Rapid Response Mechanism petitions filed, bringing total to over 30.', isFuture: false },
    ],
    changelog: [
      { date: '2026-06-01', summary: 'USMCA Rapid Response Mechanism invoked in two new facilities', detail: 'The US Trade Representative announced the filing of two new Rapid Response Mechanism petitions concerning alleged denial of workers rights at manufacturing facilities in Monterrey and Tijuana. The petitions were filed at the request of worker coalitions and relate to interference with union organising and collective bargaining. Mexican authorities have 45 days to respond with a remediation plan or face tariff action.' },
    ],
    sources: [
      { type: 'Official text', title: 'USMCA Labour Chapter and Rapid Response Mechanism', url: 'https://ustr.gov/', organisation: 'US Trade Representative' },
    ],
    order: 18,
  },
];

export const STATIC_ARTICLES = [
  {
    title: 'The goalposts have moved',
    slug: 'the-goalposts-have-moved',
    category: 'From the Field',
    publishedAt: '2026-06-01',
    readTime: 8,
    excerpt: 'After two years of CSDDD transposition, the rules Global South suppliers were told to prepare for have shifted again. This is what the recalibration looks like from a supply chain practitioner\'s vantage point.',
    deck: 'The rules keep changing. For those of us advising suppliers on HREDD compliance, the moving goalposts are not an abstraction.',
    authorName: 'Vir Mehta',
    authorRole: 'Manager, Decent Work and PMEL, Solidaridad Asia',
    authorBio: 'Vir Mehta works across South and Southeast Asia and East Africa on supply chain sustainability, decent work, and human rights due diligence. He is the architect of Solidaridad Asia\'s CSDDD toolkit, piloted across India, Ethiopia, and Sri Lanka. The views expressed are his own.',
    body: [
      { type: 'paragraph', text: 'Two years ago, when the EU CSDDD transposition process was announced, we told our supply chain partners: prepare for July 2026. We ran workshops, we developed self-assessment tools, we worked with cooperatives in Tamil Nadu and Andhra Pradesh to document their grievance mechanisms and map their tier-two suppliers. The work was real, the investment was significant, and the understanding that emerged from it was genuinely useful.' },
      { type: 'paragraph', text: 'And then the goalposts moved. The transposition deadline has been pushed to July 2027. The scope thresholds have been revised. The sector-specific provisions that would have applied to high-risk sectors first have been substantially weakened. For those of us in the field, this is not an abstraction. It is a renegotiation of a social contract that many suppliers invested heavily in meeting.' },
      { type: 'h2', text: 'What the extension actually means' },
      { type: 'paragraph', text: 'The one-year extension to the transposition deadline does not mean that nothing will happen before July 2027. Several EU member states are likely to transpose early, or have already transposed the CSDDD into national law in ways that extend obligations to suppliers immediately. Germany\'s LkSG remains in force and is being actively enforced. France\'s Duty of Vigilance Law is generating litigation. The European compliance environment has not paused.' },
      { type: 'paragraph', text: 'What the extension does mean is that the pressure on the smallest and most resource-constrained suppliers has momentarily eased. For a tea cooperative in Karnataka or a garment manufacturer in Tirupur, a twelve-month delay in the deadline is twelve months in which buyers may be marginally less urgent in their documentation demands. That is real breathing room, even if it is not a reprieve.' },
      { type: 'h2', text: 'What we should do with the time' },
      { type: 'paragraph', text: 'The instinct, for consultants and NGOs alike, is to use compliance delays to do the work we always wanted to do but never had time for: building supplier capacity rather than just collecting supplier data, creating grievance mechanisms that workers actually trust rather than mechanisms that satisfy audit checklists, and designing due diligence processes around the actual risk profile of specific supply chains rather than generic sector-level assumptions. The delay gives us the window. The question is whether our buyers and development partners have the patience to use it that way.' },
    ],
    referencedLaws: ['eu-csddd', 'german-supply-chain-act-lksg', 'french-duty-of-vigilance-law'],
  },
  {
    title: 'The German LkSG at two years: what enforcement has actually looked like',
    slug: 'german-lksG-at-two-years',
    category: 'Legal Analysis',
    publishedAt: '2026-05-15',
    readTime: 12,
    excerpt: 'Germany\'s supply chain law came into force in January 2023 with considerable fanfare. A close reading of BAFA\'s enforcement actions reveals a pattern that should concern suppliers in South and Southeast Asia.',
    deck: 'Enforcement under the LkSG has been slower than its critics feared and less toothless than its defenders claimed. The pattern that has emerged deserves careful attention.',
    authorName: 'Dr. Priya Nair',
    authorRole: 'Research Fellow, Institute for Responsible Business',
    authorBio: 'Dr. Priya Nair is a research fellow specialising in comparative business and human rights law, with a focus on enforcement mechanisms and their practical effects on Global South supply chains. She holds a doctorate in international trade law from the National Law School of India University.',
    body: [
      { type: 'paragraph', text: 'The German Lieferkettensorgfaltspflichtengesetz celebrated its third year in force in January 2026. In that time, the Federal Office for Economic Affairs and Export Control (BAFA) has issued seven formal enforcement actions, opened dozens of informal compliance inquiries, and published five guidance documents clarifying how the law applies in practice. We now have enough data to say something meaningful about what enforcement actually looks like.' },
      { type: 'paragraph', text: 'The picture that emerges is more nuanced than either the law\'s critics or its defenders predicted. Enforcement has not been aggressive in the sense of large fines against major brands. But BAFA has been consistent in identifying a specific category of violation: inadequate grievance mechanisms.' },
      { type: 'h2', text: 'The grievance mechanism pattern' },
      { type: 'paragraph', text: 'Of the seven formal enforcement actions that BAFA has issued, at least four relate primarily or substantially to failures of grievance mechanism design or accessibility. The pattern is significant. BAFA is not primarily targeting companies for failing to find labour violations in their supply chains. It is targeting companies for failing to create the conditions under which labour violations could be identified and reported.' },
      { type: 'paragraph', text: 'This matters enormously for Global South suppliers. If your German buyer is under pressure to establish an adequate grievance mechanism, the mechanism needs to be accessible to workers in your facilities. A phone hotline in German, reachable only during Central European business hours, does not meet this standard. BAFA has been clear that mechanisms must be accessible in relevant local languages and through channels that workers in different cultural and technological contexts can actually use.' },
      { type: 'h2', text: 'The indirect supplier question' },
      { type: 'paragraph', text: 'The law\'s treatment of indirect suppliers, those beyond the direct supplier relationship, has been more cautious than many anticipated. BAFA\'s updated guidance confirms that obligations to investigate indirect suppliers arise only when companies have substantiated knowledge of potential violations at that tier. "Substantiated knowledge" is a meaningful threshold: generic sector-level risk is not sufficient. This limits the immediate due diligence reach of the law for most supply chains beyond the first tier.' },
      { type: 'paragraph', text: 'For suppliers, this means that pressure from German buyers is likely to remain focused on direct relationships in the near term. The documentation requests, audit requirements, and grievance mechanism demands will concentrate on first-tier suppliers. That remains significant, but it is different from the scenario many feared, in which every tier of every supply chain would be under immediate scrutiny.' },
    ],
    referencedLaws: ['german-supply-chain-act-lksg'],
  },
  {
    title: 'Grievance mechanisms on paper and in practice',
    slug: 'grievance-mechanisms-on-paper-and-in-practice',
    category: 'Implementation',
    publishedAt: '2026-04-10',
    readTime: 9,
    excerpt: 'Most HREDD frameworks require companies to establish operational-level grievance mechanisms. The gap between what those mechanisms look like on paper and what workers actually encounter is significant, and systematically underdiscussed.',
    deck: 'A grievance mechanism that workers cannot find, do not trust, or cannot use in their own language is not a grievance mechanism. It is a compliance artefact.',
    authorName: 'Tanvir Ahmed',
    authorRole: 'Independent supply chain consultant, Dhaka',
    authorBio: 'Tanvir Ahmed has spent fourteen years working on labour rights and supply chain accountability across South and Southeast Asia, with a particular focus on the garment sector in Bangladesh. He currently works independently with brands, suppliers, and civil society organisations on grievance mechanism design and implementation.',
    body: [
      { type: 'paragraph', text: 'I have reviewed more than sixty operational-level grievance mechanisms over the past three years, across garment factories, tea estates, electronics assembly facilities, and agricultural cooperatives in Bangladesh, India, Sri Lanka, and Vietnam. The quality range is vast. At one end, there are mechanisms that workers genuinely trust, use, and that have produced real remediation outcomes. At the other end, there are PDF documents with a phone number that no one has answered in eleven months.' },
      { type: 'paragraph', text: 'The HREDD legislative frameworks emerging from Europe are, quite rightly, beginning to focus on grievance mechanism effectiveness rather than just existence. BAFA\'s enforcement pattern under the German LkSG is the clearest signal: a mechanism that exists only on paper is not a mechanism. But even "effectiveness" can be measured in ways that miss the point.' },
      { type: 'h2', text: 'The audit-readiness trap' },
      { type: 'paragraph', text: 'The most common failure mode I encounter is what I call the audit-readiness trap: a grievance mechanism designed to satisfy an auditor\'s checklist rather than to serve the workers it is meant to protect. These mechanisms have all the right elements. There is a policy. There is a procedure. There is a hotline number. There may even be a third-party administrator. But workers do not know about it, do not trust it, or cannot use it in any meaningful way.' },
      { type: 'paragraph', text: 'The design failure usually happens at the beginning of the process. Someone in a compliance department reads the relevant standard, identifies the required elements, and assembles them. The mechanism is then presented to auditors as evidence of compliance. Workers are informed of its existence through a notice in the canteen or a line in the employment contract. No one asks whether the mechanism is accessible, culturally appropriate, or trusted by the people it is supposed to serve.' },
      { type: 'h2', text: 'What effective mechanisms actually look like' },
      { type: 'paragraph', text: 'The mechanisms I have seen that genuinely work share several characteristics that are not on most compliance checklists. They were co-designed with worker representatives. They offer multiple channels, because different workers have different comfort levels with different formats. They have local language interfaces, not just local language translation of an English-language system. And they have demonstrated to workers, through visible examples of remediation, that using the mechanism can actually produce change.' },
      { type: 'paragraph', text: 'The last point is the most important and the hardest to manufacture. Trust in a grievance mechanism is built through outcomes, not design. A mechanism that workers have used and seen produce results is trusted. A mechanism that workers have used and seen produce nothing is worse than no mechanism at all, because it tells workers that raising concerns is pointless.' },
    ],
    referencedLaws: ['german-supply-chain-act-lksg', 'eu-csddd', 'french-duty-of-vigilance-law'],
  },
  {
    title: 'How a Sri Lankan tea cooperative survived its first HREDD audit',
    slug: 'sri-lankan-tea-cooperative-hredd-audit',
    category: 'Case Studies',
    publishedAt: '2026-03-01',
    readTime: 7,
    excerpt: 'When a German buyer notified a Kandy cooperative that it would conduct a supply chain audit under LkSG requirements, the cooperative had eight weeks to prepare. This is what that process looked like from the inside.',
    deck: 'The audit lasted three days. The preparation took eight weeks. The real work, it turned out, had started three years earlier.',
    authorName: 'Amali Perera',
    authorRole: 'Sustainability coordinator, Ceylon Tea Cooperative Consortium',
    authorBio: 'Amali Perera leads sustainability and certification programmes for the Ceylon Tea Cooperative Consortium, a network of fourteen smallholder cooperatives in the Kandy and Nuwara Eliya districts of Sri Lanka. She holds a degree in environmental management from the University of Peradeniya.',
    body: [
      { type: 'paragraph', text: 'The email arrived on a Tuesday morning in October. Our German buyer, a specialty tea importer based in Hamburg, was informing us that they would be conducting a supply chain audit under the German Supply Chain Act (LkSG) requirements. The audit would take place in early December. We had eight weeks.' },
      { type: 'paragraph', text: 'I will be honest: my first reaction was something between panic and resentment. We are a cooperative of smallholder tea farmers, many of whom manage less than two hectares. We have been working on sustainability certifications since 2018. We have Rainforest Alliance certification, strong internal social auditing, and a documented grievance mechanism that our member farmers actually use. And now we were being asked to demonstrate compliance with a German law that we had never heard of until six months earlier.' },
      { type: 'h2', text: 'What the auditors actually wanted' },
      { type: 'paragraph', text: 'The first thing we did was contact Solidaridad, who had done some preliminary LkSG training with us earlier in the year. They helped us understand what the auditors were actually looking for: documented risk assessment, evidence of a grievance mechanism, records of any violations found and what we had done about them, and our policies on child labour, forced labour, and freedom of association.' },
      { type: 'paragraph', text: 'The good news was that most of what we needed existed. Our Rainforest Alliance certification process had generated a significant amount of the documentation that the auditors wanted. Our internal grievance records showed fourteen complaints received over the past two years, all documented, eleven resolved, three ongoing. This was actually the most important thing we showed the auditors: evidence that the mechanism worked and that we used it.' },
      { type: 'h2', text: 'What we had to build from scratch' },
      { type: 'paragraph', text: 'The gap was documentation. We had the practices, but we did not always have the paper trail. Our risk assessment was largely in the heads of our field officers rather than in a written document. Our corrective action process was well understood internally but not formally described. We spent the eight weeks converting institutional knowledge into documented procedures.' },
      { type: 'paragraph', text: 'The audit lasted three days. The lead auditor spent the first day reviewing documents, the second day visiting two of our larger member farms, and the third day in a closing meeting where she presented findings and agreed next steps. We received a conditional compliance status, with two areas for improvement: a more systematic approach to indirect supplier risk assessment, and a formal policy statement on freedom of association in our own internal governance. Both were addressed within ninety days. We remain on the preferred supplier list.' },
    ],
    referencedLaws: ['german-supply-chain-act-lksg'],
  },
];

export const STATIC_SITE_SETTINGS = {
  currentVolume: 1,
  currentIssue: 1,
  currentMonth: 'June 2026',
  trackerLastUpdated: 'June 2026',
  trackerNextUpdate: 'July 2026',
  editorialQuote: 'These laws were written about us, without us. The least we can do is understand them well enough to play the game on our own terms.',
  movementsThisMonth: [
    {
      lawName: 'EU CSDDD',
      jurisdiction: 'European Union',
      summary: 'Transposition deadline extended to July 2027. Member states have one additional year to incorporate the directive into national law.',
    },
    {
      lawName: 'German LkSG',
      jurisdiction: 'Germany',
      summary: 'BAFA issues its seventh enforcement action, targeting inadequate grievance mechanism accessibility at a direct supplier in South Asia.',
    },
    {
      lawName: 'India BRSR Core',
      jurisdiction: 'India',
      summary: 'SEBI extends mandatory disclosure obligations to the top 500 listed companies, up from the top 150, effective from FY 2025-26.',
    },
  ],
};
