export const STATIC_LAWS = [
  {
    _id: 'law-lksg',
    name: 'Supply Chain Due Diligence Act',
    nativeName: 'Lieferkettensorgfaltspflichtengesetz',
    slug: 'lksg',
    jurisdiction: 'Germany',
    iso: 'DEU',
    year: 2021,
    inForce: '2023-01-01',
    status: 'in-force',
    scope: 'Companies with 1,000+ employees in Germany, or foreign companies with a German branch of equivalent size.',
    provisions: [
      { title: 'Annual risk analysis', text: 'Comprehensive risk analysis of own operations, direct suppliers, and where there is substantiated knowledge of violations, indirect supply chains.' },
      { title: 'Preventive measures', text: 'Implement preventive measures including supplier codes of conduct, training, and contractual audit rights.' },
      { title: 'Grievance mechanism', text: 'Establish an accessible grievance mechanism for workers and third parties to report violations.' },
      { title: 'Remediation', text: 'When violations are identified, develop and implement a remediation plan with a clear timeline and measurable outcomes.' },
      { title: 'Annual reporting', text: 'Document due diligence efforts and publish an annual report on the BAFA platform.' },
    ],
    timeline: [
      { date: '2021-06-11', event: 'Act passed by Bundestag' },
      { date: '2023-01-01', event: 'In force for companies with 3,000+ employees' },
      { date: '2024-01-01', event: 'Extended to companies with 1,000+ employees' },
    ],
    relatedLaws: [],
  },
  {
    _id: 'law-loi-vigilance',
    name: 'Duty of Vigilance Law',
    nativeName: 'Loi relative au devoir de vigilance',
    slug: 'loi-vigilance',
    jurisdiction: 'France',
    iso: 'FRA',
    year: 2017,
    inForce: '2017-03-27',
    status: 'in-force',
    scope: 'French companies with 5,000+ employees in France, or 10,000+ worldwide including subsidiaries.',
    provisions: [
      { title: 'Vigilance plan', text: 'Publish and implement a vigilance plan covering human rights, health, safety, and the environment across operations, subsidiaries, and established commercial relationships.' },
      { title: 'Risk mapping', text: 'Identify and prioritise risks in own operations, subsidiaries, subcontractors, and suppliers.' },
      { title: 'Regular assessment', text: 'Establish procedures to regularly assess subsidiaries, subcontractors, and suppliers.' },
      { title: 'Mitigation actions', text: 'Describe specific actions taken to mitigate identified risks.' },
      { title: 'Alert mechanism', text: 'Implement an alert mechanism to collect reports from persons witnessing serious violations.' },
    ],
    timeline: [
      { date: '2015-03-30', event: 'Bill introduced following Rana Plaza disaster' },
      { date: '2017-02-21', event: 'Adopted by National Assembly' },
      { date: '2017-03-27', event: 'Enacted into law' },
    ],
    relatedLaws: [],
  },
  {
    _id: 'law-apenhetsloven',
    name: 'Transparency Act',
    nativeName: 'Apenhetsloven',
    slug: 'transparency-act-norway',
    jurisdiction: 'Norway',
    iso: 'NOR',
    year: 2021,
    inForce: '2022-07-01',
    status: 'in-force',
    scope: 'Larger Norwegian enterprises and foreign enterprises selling goods or services to Norwegian end users.',
    provisions: [
      { title: 'OECD-based due diligence', text: 'Conduct due diligence in accordance with the OECD Guidelines for Multinational Enterprises.' },
      { title: 'Annual due diligence report', text: 'Publish an annual account of due diligence assessments, identifying the most salient human rights risks.' },
      { title: 'Right to information', text: 'Respond within three weeks to written requests from the public about due diligence.' },
    ],
    timeline: [
      { date: '2021-06-18', event: 'Act passed by Storting' },
      { date: '2022-07-01', event: 'Entered into force' },
    ],
    relatedLaws: [],
  },
  {
    _id: 'law-csddd',
    name: 'Corporate Sustainability Due Diligence Directive',
    nativeName: 'CS3D',
    slug: 'csddd',
    jurisdiction: 'European Union',
    iso: null,
    year: 2024,
    inForce: null,
    status: 'pending',
    scope: 'EU companies with 1,000+ employees and EUR 450M+ net worldwide turnover. Phased implementation 2027-2029.',
    provisions: [
      { title: 'Adopt a due diligence policy', text: 'Adopt and maintain an annual due diligence policy describing approach across operations and value chains.' },
      { title: 'Map and assess adverse impacts', text: 'Identify actual and potential adverse human rights and environmental impacts in own operations, subsidiaries, and business partners.' },
      { title: 'Prevent and mitigate potential impacts', text: 'Take appropriate measures to prevent or mitigate potential adverse impacts, including through contractual assurances.' },
      { title: 'Cease, remediate, and restore', text: 'Where actual adverse impacts occur, cease the activity causing harm or minimise it, and provide remediation to those affected.' },
      { title: 'Climate transition plan', text: 'Adopt and put into effect a climate transition plan aligned with the Paris Agreement.' },
      { title: 'Complaints and notification procedure', text: 'Establish a procedure for persons and organisations to submit complaints about actual or potential adverse impacts.' },
      { title: 'Annual communication', text: 'Report on due diligence annually, consistent with the Corporate Sustainability Reporting Directive where applicable.' },
    ],
    timeline: [
      { date: '2022-02-23', event: 'Commission proposal published' },
      { date: '2024-04-24', event: 'European Parliament adopted text' },
      { date: '2024-07-25', event: 'Directive entered into force' },
      { date: '2026-07-26', event: 'Transposition deadline for member states' },
      { date: '2027-07-26', event: 'First companies in scope (5,000+ employees, EUR 1.5bn+ turnover)' },
    ],
    relatedLaws: [],
  },
  {
    _id: 'law-wkba',
    name: 'Child Labour Due Diligence Act',
    nativeName: 'Wet zorgplicht kinderarbeid',
    slug: 'wkba',
    jurisdiction: 'Netherlands',
    iso: 'NLD',
    year: 2019,
    inForce: null,
    status: 'pending',
    scope: 'All companies selling goods or services to Dutch end users with turnover above EUR 3M, regardless of country of establishment.',
    provisions: [
      { title: 'Declaration of care', text: 'Submit a statement of due diligence to the Authority for the Financial Markets.' },
      { title: 'Investigation', text: 'Investigate whether child labour occurs anywhere in the supply chain.' },
      { title: 'Action plan', text: 'Draw up and implement an action plan if child labour is found or reasonably suspected.' },
      { title: 'Public availability', text: 'Make the declaration of due diligence publicly available on the company website.' },
    ],
    timeline: [
      { date: '2019-05-14', event: 'Act passed by Senate' },
      { date: '2022-01-01', event: 'Original entry into force delayed' },
      { date: '2025-01-01', event: 'Act entered into force' },
    ],
    relatedLaws: [],
  },
  {
    _id: 'law-msa',
    name: 'Modern Slavery Act',
    nativeName: null,
    slug: 'modern-slavery-act',
    jurisdiction: 'United Kingdom',
    iso: 'GBR',
    year: 2015,
    inForce: '2015-10-29',
    status: 'in-force',
    scope: 'Commercial organisations with annual turnover of GBP 36M+ supplying goods or services in the UK.',
    provisions: [
      { title: 'Annual transparency statement', text: 'Publish an annual Modern Slavery and Human Trafficking Statement describing steps taken to ensure slavery and trafficking are not occurring in operations or supply chains.' },
      { title: 'Supply chain disclosure', text: 'Disclose the steps taken to ensure modern slavery is not present in supply chains.' },
      { title: 'Board approval', text: 'Statement must be approved by the board of directors and signed by a director.' },
    ],
    timeline: [
      { date: '2015-03-26', event: 'Act passed by Parliament' },
      { date: '2015-10-29', event: 'Section 54 (Transparency in Supply Chains) entered into force' },
    ],
    relatedLaws: [],
  },
  {
    _id: 'law-uflpa',
    name: 'Uyghur Forced Labor Prevention Act',
    nativeName: null,
    slug: 'uflpa',
    jurisdiction: 'United States',
    iso: 'USA',
    year: 2021,
    inForce: '2022-06-21',
    status: 'in-force',
    scope: 'Any importer of goods into the United States. Creates a rebuttable presumption that goods from Xinjiang were produced with forced labour.',
    provisions: [
      { title: 'Supply chain traceability', text: 'Importers with any potential connection to Xinjiang must trace supply chains and demonstrate goods were not produced with forced labour.' },
      { title: 'Rebut presumption', text: 'If goods are detained, importers must provide clear and convincing evidence to CBP that goods were not produced with forced labour.' },
      { title: 'Monitor entity list', text: 'Importers must regularly monitor the CBP entity list and ensure supply chains do not connect to listed entities.' },
    ],
    timeline: [
      { date: '2021-12-23', event: 'UFLPA enacted' },
      { date: '2022-06-21', event: 'Enforcement begins; CBP entity list published' },
    ],
    relatedLaws: [],
  },
  {
    _id: 'law-australia-msa',
    name: 'Modern Slavery Act',
    nativeName: null,
    slug: 'australia-modern-slavery-act',
    jurisdiction: 'Australia',
    iso: 'AUS',
    year: 2018,
    inForce: '2019-01-01',
    status: 'in-force',
    scope: 'Entities with annual consolidated revenue over AUD 100M that carry on business in Australia.',
    provisions: [
      { title: 'Annual modern slavery statement', text: 'Prepare a statement addressing seven mandatory criteria, including supply chain risk assessment and due diligence processes.' },
      { title: 'Board approval', text: 'Statement must be approved by the principal governing body and signed by a responsible member.' },
      { title: 'Public disclosure', text: 'Submit statement to the government and publish on the company website.' },
    ],
    timeline: [
      { date: '2018-11-29', event: 'Act received Royal Assent' },
      { date: '2019-01-01', event: 'Act entered into force' },
      { date: '2026-01-01', event: 'Government signals intent to introduce mandatory due diligence amendments' },
    ],
    relatedLaws: [],
  },
  {
    _id: 'law-swiss-rbo',
    name: 'Responsible Business Ordinance',
    nativeName: 'Verordnung uber Sorgfaltspflichten und Transparenz bezuglich Mineralien und Metallen aus Konfliktgebieten und Kinderarbeit',
    slug: 'swiss-responsible-business-ordinance',
    jurisdiction: 'Switzerland',
    iso: 'CHE',
    year: 2022,
    inForce: '2022-01-01',
    status: 'in-force',
    scope: 'Large Swiss companies importing or processing minerals and metals from conflict-affected areas, and companies with supply chain child labour risks.',
    provisions: [
      { title: 'Conflict minerals due diligence', text: 'Companies importing tin, tantalum, tungsten, or gold from conflict-affected areas must conduct due diligence in line with OECD guidance.' },
      { title: 'Child labour due diligence', text: 'Companies with supply chains in countries with elevated child labour risks must conduct due diligence to identify and address child labour.' },
      { title: 'Annual reporting', text: 'Covered companies must publish an annual due diligence report on supply chain practices.' },
    ],
    timeline: [
      { date: '2020-11-29', event: 'Responsible Business Initiative rejected in referendum' },
      { date: '2022-01-01', event: 'Ordinance enters into force (conflict minerals and child labour)' },
    ],
    relatedLaws: [],
  },
  {
    _id: 'law-canada-flcca',
    name: 'Fighting Against Forced Labour and Child Labour in Supply Chains Act',
    nativeName: null,
    slug: 'canada-flcca',
    jurisdiction: 'Canada',
    iso: 'CAN',
    year: 2023,
    inForce: '2024-01-01',
    status: 'in-force',
    scope: 'Government institutions and private entities listed on a Canadian stock exchange or meeting size thresholds that produce, sell, distribute, or import goods in Canada.',
    provisions: [
      { title: 'Annual supply chain report', text: 'Submit an annual report to the Minister describing supply chains, policies on forced and child labour, due diligence processes, and training provided.' },
      { title: 'Public availability', text: 'Publish the report on the entity website and submit to the government within six months of the financial year end.' },
    ],
    timeline: [
      { date: '2023-05-11', event: 'Act enacted' },
      { date: '2024-01-01', event: 'Act entered into force' },
      { date: '2025-05-01', event: 'First reporting cycle complete' },
    ],
    relatedLaws: [],
  },
];

export const STATIC_ARTICLES = [
  {
    _id: 'article-omnibus',
    title: 'On the quiet drafting of the EU Omnibus',
    slug: 'eu-omnibus-csddd',
    deck: "The Council's forty-page Omnibus proposal would narrow CSDDD's civil-liability provision. We read it.",
    category: 'Analysis',
    author: 'The Editors',
    publishedAt: '2026-04-04',
    readTime: 7,
    body: [
      { type: 'paragraph', text: 'The European Council published a forty-page Omnibus proposal last month that would, among other things, narrow the scope of the CSDDD civil-liability provision. The proposal has attracted relatively little attention in the mainstream press. We read it.' },
      { type: 'paragraph', text: 'Three things are worth noting. First, the civil liability change is more significant than the headline numbers suggest. The current Directive text creates liability where a company fails to comply with its due diligence obligations and that failure causes damage. The Omnibus would add a further requirement: the damage must be caused by a specific identified failure in the due diligence process, not merely by the overall inadequacy of the system. That is a meaningfully higher bar for plaintiffs.' },
      { type: 'paragraph', text: 'Second, the proposal also touches the scope thresholds. The current thresholds of 1,000 employees and EUR 450M turnover would be raised to 3,000 employees and EUR 900M turnover in the first phase of application. Several hundred companies that had been planning for CSDDD compliance by 2027 would find themselves outside scope entirely.' },
      { type: 'paragraph', text: 'Third, there is one change in the proposal we cannot yet fully explain: a new exemption for companies that have obtained third-party certifications under an unspecified approved scheme. The mechanism for approving these schemes is not described. We will be watching.' },
    ],
  },
  {
    _id: 'article-lksg-year-one',
    title: 'The LkSG at year one: what enforcement actually looks like',
    slug: 'lksg-year-one',
    deck: 'Germany\'s Supply Chain Act turned one in January. The Federal Office for Economic Affairs has issued formal notices. Here is what they cover.',
    category: 'Legal Analysis',
    author: 'The Editors',
    publishedAt: '2026-03-14',
    readTime: 9,
    body: [
      { type: 'paragraph', text: 'The German Supply Chain Act has now been in force for over two years. The pattern of enforcement that has emerged is important for suppliers in South and Southeast Asia to understand.' },
      { type: 'paragraph', text: 'Of the formal enforcement actions that BAFA has issued, most relate primarily or substantially to failures of grievance mechanism design or accessibility. BAFA is not primarily targeting companies for failing to find labour violations in their supply chains. It is targeting companies for failing to create the conditions under which labour violations could be identified and reported.' },
      { type: 'h2', text: 'What this means for suppliers' },
      { type: 'paragraph', text: 'If your German buyer is under pressure to establish an adequate grievance mechanism, that mechanism needs to be accessible to workers in your facilities. A phone hotline in German, reachable only during Central European business hours, does not meet this standard. BAFA has been clear that mechanisms must be accessible in relevant local languages and through channels that workers can actually use.' },
    ],
  },
  {
    _id: 'article-norway',
    title: "Norway's right-to-know provision and what it means for suppliers",
    slug: 'norway-transparency-act-suppliers',
    deck: 'Any member of the public can now request due diligence information from a Norwegian importer. This piece explains the mechanics.',
    category: 'Implementation',
    author: 'The Editors',
    publishedAt: '2026-02-21',
    readTime: 6,
    body: [
      { type: 'paragraph', text: 'The Norwegian Transparency Act creates a right that is unusual among HREDD frameworks: any person can request information from a Norwegian company about how it addresses human rights risks in its supply chain, and the company must respond within three weeks.' },
      { type: 'paragraph', text: 'In practice, this has been used primarily by civil society organisations and journalists. But the provision has a broader structural effect: it creates an incentive for Norwegian companies to have substantive, specific information about their supply chain practices, because vague or evasive responses to information requests can be escalated to the Norwegian Consumer Authority.' },
    ],
  },
  {
    _id: 'article-global-south',
    title: 'What Global South manufacturers need to prepare for CSDDD',
    slug: 'csddd-global-south-manufacturers',
    deck: 'The Directive will not apply directly to suppliers outside the EU. But their buyers will pass the obligations downstream. This is what that looks like in practice.',
    category: 'From the Field',
    author: 'The Editors',
    publishedAt: '2026-01-30',
    readTime: 11,
    body: [
      { type: 'paragraph', text: 'The CSDDD does not apply directly to suppliers based outside the EU. But the obligations it imposes on EU companies will be transmitted through supply chains in ways that will affect manufacturers in India, Bangladesh, Vietnam, and across the Global South.' },
      { type: 'paragraph', text: 'The most immediate effect will be information requests. EU companies subject to the Directive will need to map their supply chains and assess risks. They cannot do this without cooperation from their suppliers. Some of these information requests will be well-designed and proportionate. Many will not be.' },
      { type: 'h2', text: 'Preparing practically' },
      { type: 'paragraph', text: 'The practical preparation for Global South manufacturers involves four things: documenting what you already do, establishing a grievance mechanism that workers can actually use, understanding which of your buyers are in scope, and building the internal knowledge to distinguish legitimate due diligence requests from compliance theatre.' },
    ],
  },
];

export const STATIC_SETTINGS = {
  vol: 'VOL I',
  issue: 5,
  issueDate: '2026-04-14',
  nextIssueDate: '2026-05-12',
};
